behaviors:
  ROMAN_Expert_PickInsert_Brain:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear # new in 21 linear, == default 0.15.1
      beta_schedule: constant # new in 21 constant, no para 0.15.1
      epsilon_schedule: linear # new in 21 linear, no para 0.15.1
      # use_recurrent: false # no in 21, para 0.15.1
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
      memory_size: 256
      sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 0.1
      gail:
        strength: 1.0
        gamma: 0.99
        encoding_size: 128 # no in 21
        use_actions: false
        demo_path: ../Assets/Demonstrations/ROMAN_Expert_PickInsert_Demo_N20.demo
    behavioral_cloning:
        demo_path: ../Assets/Demonstrations/ROMAN_Expert_PickInsert_Demo_N20.demo
        strength: 0.5
        steps: 800000
    max_steps: 96e6
    time_horizon: 1000
    summary_freq: 80000